name: Terraform Automation with Destroy
 
on:
  workflow_dispatch: 

jobs:
  terraform:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: eu-central-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
        

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'  # Only apply for pushes to 'main'
        run: terraform apply -auto-approve
        

      - name: Terraform Destroy
        if: github.event_name == 'workflow_dispatch'  # Run only on manual trigger
        run: terraform destroy -auto-approve
        
